### ISSUE TITLE
Alt+P goes to puzzle editor (mac)

### ISSUE THREAD

**Issue by ehne** [Cheeseness/icicle#2]
Alt+P (alt+shift+p) goes to the puzzle editor on mac
working on it!

**Comment by Cheeseness** [comment]
Yep, Alt+P is desired behaviour as documented in the [Editor Reference wiki page](https://github.com/Cheeseness/icicle/wiki/Editor-Reference#common-controls) in the Misc section under Common Controls.

Since I'm planning to rework a lot of keyboard input handling stuff, I'm comfortable considering Alt+Shift+P also launching the puzzle editor as a non-issue and will close this one.

Thanks for the report!

**Comment by ehne** [comment]
its just that  in you email it says `* Give it a play test (Alt+P with a scene selected)`

**Comment by Cheeseness** [comment]
Ahh, darn. That's totally an typo. That's what I get for writing emails at 2am!

**Comment by Cheeseness** [comment]
Just to follow up on this, the [Quick Example Workflow](https://github.com/Cheeseness/icicle/wiki/Tutorials#quick-example-workflow) section of the tutorial page has a version of the steps from the email with that typo corrected.
